version: "3"
services:
  api:
    container_name: aws-file-upload
    image: node:14
    working_dir: /usr/src/aws-file-upload
    restart: always
    command: bash -c "npm install --only=prod && npm install -D nodemon && npm run debug"
    environment:
      - PORT=3000
    volumes:
      - ./dist/:/usr/src/aws-file-upload/dist/
      - ./package.json:/usr/src/aws-file-upload/package.json
    ports:
      - "3001:3001"
      - "9222:9222"
